version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 'app'
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'psql'
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=app",
          "--dbname=psql",
          "--host=127.0.0.1",
          "--port=5432"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
    networks:
      - local
    volumes:
      - './development/resources/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - "5433:5432"

  unleash:
    image: unleashorg/unleash-server:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgres://app:app@db/unleash'
      DATABASE_SSL: 'false'
      LOG_LEVEL: 'debug'
      HTTP_PORT: '80'
      INIT_CLIENT_API_TOKENS: '*:development.fbae2f52d1b398f9f2e48a92b9307ff8d599429f9ef5fd002c85a389'
      INIT_FRONTEND_API_TOKENS: '*:development.4c0d7a93d8a6fce314daad57112905263ad8b272d46e50cf8bf6a471'
      INIT_ADMIN_API_TOKENS: '*:*.2b675a0884f3b350e8acf211dda68ea441df6527658202eeb58ea98f'
    networks:
      - local
    ports:
      - '4242:80'

networks:
  local:
