name: changelog
run-name: Changelog Update
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update CHANGELOG file
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          excludeTypes: "build,gh,other,style"
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'gh: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
