name: test-runner
run-name: Test Runner
on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: '1.11.1.1347'
          bb: '1.3.181'

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Run Tests
        run: clojure -Srepro -M:test:dev:poly test :all-bricks project:dev

  integration-testing:
    runs-on: ubuntu-latest
    needs:
      - unit-testing
    env:
      DB_NAME: 'psql'
      DB_USER: 'app'
      DB_PASSWORD: 'app'
    services:
      database:
       image: postgres:15
       env:
         POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
         POSTGRES_USER: ${{ env.DB_USER }}
         POSTGRES_DB: ${{ env.DB_NAME }}
       ports:
         - "5432:5432"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: '1.11.1.1347'
          bb: '1.3.181'

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Run Tests
        run: clojure -Srepro -M:test:dev:poly test :all-bricks project:itests
